version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    env_file:
      - .env
    ports:
      - "$APP_PORT:$APP_PORT"
    depends_on:
      - db
    restart: on-failure

volumes:
  database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/database
