"""empty message

Revision ID: 3bf83e84a1b2
Revises: 5c092ecdf1c0
Create Date: 2021-11-25 22:58:58.000066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3bf83e84a1b2"
down_revision = "5c092ecdf1c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
