"""create user table

Revision ID: 3efa60298ced
Revises: 
Create Date: 2021-11-25 20:03:44.298045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3efa60298ced"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
